name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check-fmt:
    uses: ./.github/workflows/check-fmt.yml

  check-lint:
    uses: ./.github/workflows/check-lint.yml
    with:
      code-changed: "true"
      save-rust-cache: ${{ github.ref == 'refs/heads/main' }}
